### ISSUE TITLE
Get error when trying with Windows 10: 

### ISSUE THREAD

**Issue by chaeunl** [IBM/aihwkit#11]
https://github.com/IBM/aihwkit/blob/f6b140cddfaf4146404744fa97bc1750bc035369/setup.py#L29

I got an error message "UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 3855: illegal multibyte sequence." This case is solved by adding _encoding="UTF-8"_ when opening file.
(i.e., _open(version_path, encoding="UTF8")_) 

Same as issues occurred at line#37.

**Comment by diego-plan9** [comment]
Thanks for reporting and for the suggestion @chaeunl ! Please note that at the moment we don't fully support Windows builds, and it will likely require some changes to the `cmake` files in order to compile correctly - full Windows support is on the pipeline, though (I have opened #12 for easier keeping track of the progress).

**Comment by diego-plan9** [comment]
Addressed the encoding issue via #13. For reference and for users that might not be using the latest `master` branch, using the [`PYTHONUTF8`](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONUTF8) environment variable for setting the locale might be a user-side alternative in similar cases - again, thanks @chaeunl !
