### ISSUE TITLE
Is Aihwkit compatible with AMD EPYC 7002 model?

### ISSUE THREAD

**Issue by nkyungmi** [IBM/aihwkit#152]
Hi again!
It feels like I question too much, but I'm now in my way of actively exploring this nice toolkit :3
I'm trying to buy a new pc with AMD EPYC 7002 CPU, but little worried that it might not compatible with aihwkit.
So before I buy, I just want to check if aihwkit works okay with AMD processor.
Would there be any issues if I use AMD CPU for aihwkit?

**Comment by diego-plan9** [comment]
No amount of questions is too many questions - we appreciate them and it helps us shape the package (and other users might benefit from the questions and answers as well)! 

While (as far as I know) we have not explicitly tested building and running using that particular CPU, we regularly use different Ryzen and AMD-based CPUs. In principle, as long as the CPU is `x86-64`  it should be fine - as a side note, there seems to be a report related to [compiling pytorch on epyc](https://github.com/pytorch/pytorch/issues/40968), but it seems to be solved by using a recent enough version of gcc (and you should not need to compile pytorch in order to be able to use `aihwkit` - mostly mentioning it for completeness).

**Comment by nkyungmi** [comment]
It's a relief to know that there would be no problems using AMD CPU with aihwkit :D
And yes, I also think I won't compile pytorch so I'll just make sure to have recent version of gcc to be safe.
Thank you for the check!!
