### ISSUE TITLE
Bias argument of set_weights issue

### ISSUE THREAD

**Issue by nkyungmi** [IBM/aihwkit#164]
## Description

Document says `set_weights` has (weight,bias) argument but when I try to change weight values using `set_weights(tensor, bias=tensor)`, error occurs and it says there's unexpected argument 'bias'

(docs: [https://aihwkit.readthedocs.io/en/latest/api/aihwkit.nn.modules.base.html?highlight=set_weights#aihwkit.nn.modules.base.AnalogModuleBase.set_weights](url))

[![s.png](https://i.postimg.cc/XqJQ90vh/s.png)](https://postimg.cc/2bsQfMhF)

## How to reproduce

1. Create model 
2. Try `model[0].analog_tile.set_weights(_any tensor_,bias=_any tensor_)`
3. Returns error message

## Expected behavior

It should work without error. However, **it works when I use 'biases'** instead of bias.

**Comment by diego-plan9** [comment]
Thanks for reporting - please note that there are two methods with the name `set_weights()` (with slightly different signatures indeed):

1. `AnalogModuleBase.set_weights(weight, bias, force_exact)`  ([doc](https://aihwkit.readthedocs.io/en/latest/api/aihwkit.nn.modules.base.html#aihwkit.nn.modules.base.AnalogModuleBase.set_weights))
2. `BaseTile.set_weights(weights, biases, realistic, n_loops)` ([doc](https://aihwkit.readthedocs.io/en/latest/api/aihwkit.simulator.tiles.base.html#aihwkit.simulator.tiles.base.BaseTile.set_weights))

From your snippet, it _looks_ like you might be trying to use the second one, but the documentation link you pasted seem to be the one from the first one. It depends on what you are trying to achieve, but in general using the method in the model (ie. the first one) tends to be safer/recommended (as it will ensure the `Tensors` used by torch stay in sync.

That is also partly the reason why the naming of the parameters is slightly different: for the first one, we aimed at staying close to torch's nomenclature (ie. as the names of the `Parameters` are `self.weight` and `self.bias`, the parameters for the function are in that singular form). For the second one, since the `Tile`s are in a "deeper" / more advanced level, the names of the arguments are closer to the nomenclature of the C++ `rpucuda` library.

**Comment by nkyungmi** [comment]
Thank you for your answer.
I didn't know there's another set-weights..! Fully understood!

**Comment by diego-plan9** [comment]
Closing as the initial question has been hopefully addressed - please comment back if needed!
