### ISSUE TITLE
Softbound synapses based on Fusi Abott modell

### ISSUE THREAD

**Issue by fcpprs** [IBM/aihwkit#181]
## Description and motivation
This may be caused by my lack of mathematical expertise and a quick solve is obvious. 
The soft-bound synapse model described by Fusi and Abbott [1] has been adopted in models for synaptic resistive devices, e.g. in the detailed study of Frascaroli et al. [2]. In their paper, they give an equation for the weight dependent weight update for potentiation and depression (Eqn. (1) and (2)) as well as respective equations for potentiation and depression in dependence of the pulse number ( Eqn. (3) and (4)). See figures below.

Now to my questions: 
- Is it currently possible to rewrite these equations so they fit in the framework of device models?
- As the model is defined for weights between 0 and 1, one would need to chose the DifferenceUnitCell module to obtain weights between -1 and 1, is that correct? 

I hope this is clear. I appreciate any help!

[1] S. Fusi; L. F. Abbott, Nature Neuroscience, Limits on the memory storage capacity of bounded synapses, 2007 (DOI: 10.1038/nn1859 )
[2] J. Frascaroli; S. Brivio; E. Covi; S. Spiga, Scientific Reports, Evidence of soft bound behaviour in analogue memristive devices for neuromorphic  computing, 2018 (DOI: 10.1038/s41598-018-25376-x )
![Frascaroli_1_2](https://user-images.githubusercontent.com/81355788/112631057-b4585c80-8e36-11eb-8e4b-51fd3fc1a650.PNG)
![Frascaroli_3_4](https://user-images.githubusercontent.com/81355788/112631060-b4f0f300-8e36-11eb-9c3e-bfdfba49ef89.PNG)

**Comment by maljoras** [comment]
Thank you very much for your question! Currently, we do not support this update behavior. We only have a `SoftBoundsDevice` mode, where the update behavior is similiar to (1) and (2) with `gamma=1`, that is the update step size changes linear with weight. 
You won't need `DifferenceUnitCell`, in our models the conductance range is scaled from -|w_min| to w_max, which can be realized with a fixed bias (reference cell) that we usually do not model explicitly (it can be modeled with `ReferenceUnitCell` if needed explicitely).  The `DifferenceUnitCell` is only for devices that are not bi-directional, such as PCM, where one device receives all positive updates and the other the negative updates and a reset and refresh would be needed to avoid saturation.  

That said, implementing your suggested update behavior as a new device model would be relatively straightforward. I'll see whether it can be done relatively quickly.

**Comment by maljoras** [comment]
Hi @fcpprs,
we have now added a new device model that implements the Fusi & Abbot synapse model, called `PowStepDevice`. See [here ](https://aihwkit.readthedocs.io/en/latest/api/aihwkit.simulator.configs.devices.html?highlight=PowStepDevice#aihwkit.simulator.configs.devices.PowStepDevice ) for explanation: 

Example: 

```python
import matplotlib.pyplot as plt
from aihwkit.utils.visualization import plot_device_compact
from aihwkit.simulator.configs.devices import PowStepDevice

plt.ion()
plot_device_compact(
    PowStepDevice(w_min=-1, w_max=1, dw_min=0.01, pow_gamma=1.1, pow_gamma_dtod=0.5,
                  pow_up_down=0.2, w_min_dtod=0.0, w_max_dtod=0.0), n_steps=1000)
plt.show()
```
![image](https://media.github.ibm.com/user/63124/files/4bc02280-9303-11eb-90f1-6b4109d6d4f3)

**Comment by fcpprs** [comment]
Hi @maljoras,

Thank you very much for this improvement, it should help me a lot!
I will leave the issue open until I have tested it out, if this is okay for you.

Great work!

**Comment by fcpprs** [comment]
Hi @maljoras ,

I have played around with the new device classe and it works great. Thank you for including it!

However, I am struggling with how the parameters α and γ are connected to the parameterization you are using. Could you elaborate how a value of  α and γ  would translate into your model?

Also, as indicated in the cited studies, it frequently occurs that the parameters are not identical for up and down (potentiation and depression) cycles. While it is possible to bias the exponent using `pow_up_down` in either direction, I could not find an option for independently setting it for up /down. Did I oversee it?

**Comment by maljoras** [comment]
Hi @fcpprs,
great that you find it useful. Yes, the gamma can be set independently for up versus down direction. Only that you set the mean value `pow_gamma` and the up/down bias `pow_up_down`, instead of directly the up and down gamma. In this way, parameter variation simulations are often better to implement. It is just a simple calculation to get the up/down gamma from this, as described [in the documentation](https://aihwkit.readthedocs.io/en/latest/api/aihwkit.simulator.configs.devices.html?highlight=PowStepDevice#aihwkit.simulator.configs.devices.PowStepDevice.pow_up_down):  
```python
gamma_up = pow_gamma * (1 + pow_up_down)
gamma_down = pow_gamma*(1 - pow_up_down)
```
which means that if you want to define your model with  `gamma_up` and `gamma_down`, then  you can easily calculate the corresponded parameters for the `PowStepDevice` in the following way:
```python
pow_gamma = (gamma_up + gamma_down) / 2
pow_up_down = (gamma_up - gamma_down) / (gamma_up + gamma_down)
```
which follows directly from the above equations.

Analogously, the slope `alpha` (which is called `dw_min` in the model in correspondence to the other models, see the [documentation](https://aihwkit.readthedocs.io/en/latest/api/aihwkit.simulator.configs.devices.html?highlight=PowStepDevice#aihwkit.simulator.configs.devices.PowStepDevice)) is defined by giving the mean `dw_min` of both directions and the up down bias in `up_down`, as described [here](https://aihwkit.readthedocs.io/en/latest/api/aihwkit.simulator.configs.devices.html?highlight=PulsedDevice#aihwkit.simulator.configs.devices.PulsedDevice.up_down). You can use the analogous equation as above if you have given `alpha_down` and `alpha_up`:
```python
dw_min = (alpha_up + alpha_down) / 2
up_down = (alpha_up - alpha_down) / (alpha_up + alpha_down)
```

**Comment by fcpprs** [comment]
Hi @maljoras,
Thank you for this kind explanation! Your solution works great.
I have no further issues in this matter. Thank you for including the model in the project!

Best regards!
