### ISSUE TITLE
Question about save / load model

### ISSUE THREAD

**Issue by darrenkao** [IBM/aihwkit#253]
## Description

 I have saved the model after training, but it will get the error below when loading the model and using to inference

RuntimeError: x_input must be a CPU tensor

## How to reproduce

Save the model -> load the model and run either inference or training

## Expected behavior

It can load model and inference or retraining fluently

## Other information

* Pytorch version: 1.8.1+cu102
* Package version: 
* OS: Ubuntu
* Python version: 3.6
* Conda version (or N/A): N/A

**Comment by diego-plan9** [comment]
Thanks for reporting @darrenkao ! Can you paste a snippet with the specific code you are using that triggers the error, and also specify which version are you using (ie. `0.3.0` from `pip install`, or if you are using the cloned repository at a specific commit from `master`)?

The reason for the second question is due to some improvements that ripple up in the way the model is serialized back and forth were introduced recently (#241 , #252 ) , and might be related to the issue you are experiencing.

Also, from the error message it seems you might be using multiple devices in your scenario - if that is the case, usually you need to take action in your code moving some entities to the desired device ([this section](https://pytorch.org/tutorials/beginner/saving_loading_models.html#saving-loading-model-across-devices) of PyTorch documentation provides more details).

**Comment by darrenkao** [comment]
I use the `clone version` and compile in my server with cuda library.
I'm sure I use cuda environment to run not only training but inference. 
1. I use a common way to save my training model
`torch.save(model.state_dict(), [PATH])`
2. In inference code, I also use same way to load them
`torch.load('PATH')`
3. Then I get the follow errors
`File "examples/11_vgg8_inference.py", line 185, in test_evaluation`
    `pred = model(images)`
 ` File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl`
    `result = self.forward(*input, **kwargs)`
  `File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 119, in forward`
    `input = module(input)`
  `File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl`
    `result = self.forward(*input, **kwargs)`
  `File "/home/lab617/darrenkao/Desktop/aihwkit/src/aihwkit/nn/modules/conv.py", line 131, in forward`
   ` self.bias, not self.training)`
  `File "/home/lab617/darrenkao/Desktop/aihwkit/src/aihwkit/nn/functions.py", line 85, in forward`
   `return analog_tile.forward_indexed(input_, is_test)`
  `File "/usr/local/lib/python3.6/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context`
    `return func(*args, **kwargs)`
  `File "/home/lab617/darrenkao/Desktop/aihwkit/src/aihwkit/simulator/tiles/base.py", line 635, in forward_indexed`
    `return self.tile.forward_indexed(x_input, d_tensor, is_test)`
`RuntimeError: x_input must be a CPU tensor`

But I have moved the entire model to cuda after loading model
 `checkpoint = torch.load('./trained_model/ReRamES4Preset_CrossEntropyLoss_0.001_100_1.pt')`
  `model.load_state_dict(checkpoint)`
  `model.cuda()`

Is there any wrong step to me?

**Comment by diego-plan9** [comment]
Thanks for the info!

Can you confirm which specific commit are you in (using `git log -n 1 --oneline`)? From the traceback, I _think_ you might not be on the most recent commit - if that is the case, could you try again using the latest version from `master` (at commit `151058b` currently) using `git pull origin master`, and report back?

This mostly as we recently (earlier today, in fact) added #252 to the repository - which seems related to the issue.

**Comment by darrenkao** [comment]
After I use latest version, the original error disappears. But there is a new error message when I try to load training model to inference pops up as below!
`AttributeError: 'Parameter' object has no attribute 'analog_tile'`
Do I need to save analog_tile info when saving training model?

**Comment by diego-plan9** [comment]
Thanks again for the information @darrenkao ! It helped confirm that indeed there is currently an issue when serializing to disk (using torch's `save()`) is involved, as the pickling is unable to reconstruct the `AnalogContext` fully after `load()`-ing (resulting in the `AttributeError` you are experiencing).

We are working currently on a fix - will update the issue as we progress.

**Comment by darrenkao** [comment]
Thanks  for your Kindly help! I will look forward for your new version!

**Comment by diego-plan9** [comment]
Thanks to @maljoras work in #257, the issue should now be fixed and a model loaded from file should now again be possible to use for training (among other improvements): @darrenkao , could you try your script after fetching the latest version, and confirm it has fixed the issue?

**Comment by darrenkao** [comment]
Yes, It works fine after I using latest version. Thanks a lot! 
Is it possible using different hardware spec when training and inference respectively?
For example, I use ideal preset to training and use ReRamES4Preset to inference to observe noise effect of a network model.

**Comment by maljoras** [comment]
Hi @darrenkao:
Glad to hear that it is working now. Regarding the hardware-ware training, yes, the hardware spec can be changed, by using `save_state_dict` in the first model and `load_state_dict` in the second model (with same network topology but with different `rpu_config`). However, note that the `presets` are only referring to the update behaviour of the material and thus are not used in case of inference, where only the forward pass matters. Hardware-aware training and inference on dedicated analog hardware for inference for different time points after programming is always handled with the `InferenceTile` and the statistical weight noise model. To change the forward spec (eg. output noise, ADC/DAC resolution etc) one needs to modify the `rpu_config.forward` parameter (of type `IOParameters`). For the programming noise model and 1/f noise and drift we use the `rpu_config.noise_model` parameters. Currently, we have only one model here, which is based on PCM data. However, it would be relatively straightforward to overload the existing one to add new models.  

If one is not interested in the drift behavior and accuracy change over time, but only the accuracy after programming, one could simulate the programming behavior by using the update pass of the training models. In this case, it might make sense in some cases to use one of the presets and turn on `realistic_read_write` for each layer (see [here](https://aihwkit.readthedocs.io/en/latest/api/aihwkit.nn.modules.linear.html?highlight=realistic#aihwkit.nn.modules.linear.AnalogLinear.realistic_read_write)) and then do an inference pass. This would simulate the writing using the characteristics of the materials.  

Please open a new issue, if you have more follow up questions, since I am closing this one as the bug is fixed. Many thanks!

**Comment by darrenkao** [comment]
Got it! Thanks!
