### ISSUE TITLE
signed computation

### ISSUE THREAD

**Issue by saba-er** [IBM/aihwkit#286]
For the purpose of signed computation, is negative weights are supported by the simulator? If so, could you please explain how it is implemented in unidirectional and bidirectional devices? 
Just for the context: it is very common to perform signed computation using differential conductance of a pair of memristors. I was wondering how this is supported in this simulator.

**Comment by maljoras** [comment]
Hi @SaBaKa2020 ,
thank you for this great question! We have as number of different approaches implemented that the user can choose. It also depends on whether to simulate analog training (where the update is done on the analog tile using pulses) or for analog inference (where the model is trained in hardware-aware manner, but the analog chip is only designed for doing inference). 

**Analog training** 
Most RPU devices by default are bidirectional. They only have one device per crosspoint and the reference device is implicitely assumed at perfect 0. However, if that assumption is too simplistic, we offer a [ReferenceUnitCell](https://aihwkit.readthedocs.io/en/latest/api/aihwkit.simulator.configs.devices.html?highlight=ReferenceUnitCell#aihwkit.simulator.configs.devices.ReferenceUnitCell) where the reference cell (which is not learnt) can be set to any value. The [VectorUnitCell](https://aihwkit.readthedocs.io/en/latest/api/aihwkit.simulator.configs.devices.html#aihwkit.simulator.configs.devices.VectorUnitCell) can be used to have multiple devices per crosspoint, which are all bi-directional. Each device model can, however, also be made uni-directional by using the [OneSidedUnitCell](https://aihwkit.readthedocs.io/en/latest/api/aihwkit.simulator.configs.devices.html?highlight=onesided#aihwkit.simulator.configs.devices.OneSidedUnitCell) where two separate devices are modeled per crosspoint (g plus and g minus), each only changing in one direction. Since this would be saturating very quickly, this unit cell also implements a refresh behavior that periodically checks and resets saturated devices and rewrites the difference to one of the devices. Our PCM preset uses this mechanism in conjunction with the mixed-precision optimizer (see [MixedPrecisionPCMPreset](https://aihwkit.readthedocs.io/en/latest/api/aihwkit.simulator.presets.configs.html?highlight=mixedprecision#aihwkit.simulator.presets.configs.MixedPrecisionPCMPreset)).     

**Analog inference**
In case of analog inference, training is done on a floating point device (with modified forward pass) and weights are only transferred to the analog tile for simulating inference. The programming noise, 1/f read noise over time, and drift is calculated using a statstical noise model (for instance [PCMLikeNoiseModel](https://aihwkit.readthedocs.io/en/latest/api/aihwkit.inference.noise.pcm.html?highlight=PCMLikeNoiseModel#aihwkit.inference.noise.pcm.PCMLikeNoiseModel)). This noise model is applied (meaning that the noise is added to the weight values) to positive and negative conductance values separately as specified with the weight to conductance converter (which assumed that positive weights are programmed solely on g plus and vice versa). So far we have implemented a [SinglePairConductanceConverter](https://aihwkit.readthedocs.io/en/latest/api/aihwkit.inference.converter.conductance.html?highlight=conductance#aihwkit.inference.converter.conductance.SinglePairConductanceConverter).  However, one could easily have more complicated mapping schemes during inference, by writing a custom converter that inherits the [BaseConductanceConverter](https://aihwkit.readthedocs.io/en/latest/api/aihwkit.inference.converter.base.html?highlight=BaseConductanceConverter#aihwkit.inference.converter.base.BaseConductanceConverter). Note that all these mapping schemes assume currently that one pass is done during forward and both currents are integrated in analog.
