### ISSUE TITLE
Variation on dwmin and gamma (slope)

### ISSUE THREAD

**Issue by nkyungmi** [IBM/aihwkit#288]
Hi, I'm currently trying to reproduce the experiment done in Tiki-Taka paper (T.Gokmen and W. Haensch, 2020).
From the paper, the values for variations on dwmin and slope are 

- dwmin : dtod = 0.3 / std(ctoc) = 0.3
- slope : dtod = 0.42

So, I put exact same value using Linear step device parameters and was able to get the same result from the paper.
![image](https://user-images.githubusercontent.com/80237043/135704262-c26b38d7-9803-4d9a-8c91-7abee15949de.png)

(A) 
From there, I tried to put variations in another way, by setting slope_up and dwmin_up (downs too) through accessing hidden_parameters. To do so, I first put all the variations (except dwmin std) into 0 when defining rpu device and I called hidden parameters from each layer of MLP (I'm using same MLP-MNIST setting - 756-256-128-10) then set as below.
_(Here, dwmin, slope A and slope C is all set to 0.001)_
![image](https://user-images.githubusercontent.com/80237043/135704441-a4c65cff-df88-4bc0-ac21-c1877a35c43b.png)

![image](https://user-images.githubusercontent.com/80237043/135704334-845cbd62-94d1-4176-a262-ab2348b1362a.png)

(Putting deviation of 0.126 on slope_up, not 0.42, was to consider that parameter slope_up = gamma*dwmin / Wmax and slope = gamma/Wmax hence slope_up-N(0,0.126) when gamma-N(0,0.42) and dwmin-N(0,0.3)) 

When I tested, the resulted accuracy was **different** so I checked **distribution of slope** and found out that two cases have different distribution of slope as below.
 
![image](https://user-images.githubusercontent.com/80237043/135704538-e0fd6556-4bb5-44b8-a4dd-75e3523e1aba.png)

(B)
Then, I tried to fit distribution of dwmin and slope to the setting of the paper, using hidden parameters emphirically.
![image](https://user-images.githubusercontent.com/80237043/135704567-22317ddf-eb30-4983-964f-be0dc5b9719d.png)![image](https://user-images.githubusercontent.com/80237043/135704572-0c1117b2-15cd-4b3c-91e9-af8f7d07a4a8.png)
The setting used for the hidden parameters are:
![image](https://user-images.githubusercontent.com/80237043/135704585-50c6ad31-5754-41f7-94dd-97488ff44ee5.png)

When I trained them, however, I got quite different result again.

![image](https://user-images.githubusercontent.com/80237043/135704593-16fddb20-4135-4b6d-b78d-f82f38e8862d.png)![image](https://user-images.githubusercontent.com/80237043/135704596-6fb43905-34fe-4a81-a8ea-dd26361488e6.png)

So my question is :
- From (A), are the values of hidden parameter set wrong from the original paper setting? If so, how can I match them?
- From (B), would there be any reason why the result are different even though the distibution of dwmin and slope are similar?

Thank you!

**Comment by maljoras** [comment]
Hi @nkyungmi,
first many thanks for the detailed questions and for using the toolkit! 

I think your finding of different model behavior in cases A and B stem from the fact that in your "hidden params"  distribution, some of the slopes are actually positive, although they should be negative to be consistent with the direction. Note that if the slopes are positive for the weight update size in the e.g. up direction, that means that weight update sizes actually increase (and not saturate) when having larger positive weights nearer to w max. Since these up updates near w max are potentially larger than the down update sizes, this is in stark disagreement with the requirement of having a well defined symmetry point for the Tiki-Taka algorithm. thus weight will actually stay large instead of decaying to zero for random inputs. This will cause the tiki-taka algorithm to fail, as you show. 

Note that the tiki-taka algorithm is very sensitive to the symmetry point being at exactly zero. You should use the `SoftBounds` device to ensure that. In this device, even when weight bounds are varied, it is ensured that the symmetry point is exactly zero. The deviation from the symmetry point can be set by the `up_down_dtod` parameter, which implicitly shifts the point away from zero. For accessing whether you model is at the symmetry point you can use the plotting tool `plot_device_symmetry` (see [here]( https://aihwkit.readthedocs.io/en/latest/api/aihwkit.utils.visualization.html?highlight=plot_symmetry#aihwkit.utils.visualization.plot_device_symmetry))    

In the AIHWKIT, the slopes are enforced to be of the correct sign by taken the absolute value ([see here](https://aihwkit.readthedocs.io/en/latest/api/aihwkit.simulator.configs.devices.html?highlight=LinearStepDevice#aihwkit.simulator.configs.devices.LinearStepDevice)). In addition, there is a "ensure_consistency" flag that weights ranges as expected. This flag is by default set to true.

Also note that the slopes and slope dtod parameters are set slightly differently defined in the AIHWKIT as in the paper Gokmen et al 2020. In the AIHWKIT, the slope variability refers to the variability of the intercept of the line at w_max and not directly on the slope parameter. See [here](https://github.com/IBM/aihwkit/blob/master/src/rpucuda/rpu_linearstep_device.cpp#L37) for the code that generates the hidden slope parameters (ls_decrease.. corresponds to gamma on the python side). It should be correctly explained with in the documentation above, however, which I think you have already understood correctly.
