### ISSUE TITLE
Question about trained weights quantization

### ISSUE THREAD

**Issue by ElinorG11** [IBM/aihwkit#301]
Hello,

I want to use weight of trained ResNet32 network for experimenting with the kit. I want to see how changing the weight quantization effect the accuracy of the network at the inference stage.

I want to try 3 types of weight precision: FP (no quantization), 8-bit and 4-bit on ideal tiles. From reviewing the source code, I found the function `set_weights()` which gets as an argument `weight matrix` and quantizes them. But I couldn't understand how can I specify the number of bins? could you please guide me to where should I look? 

moreover, from you documentation I thought the kit could quantize the weights only to 8 or 4 bits (or not quantize at all), but here it looks like I can set any level of quantization, even quantize it into 2-bits. perhaps I've misunderstood something?

Thank you very much for your support.

**Comment by maljoras** [comment]
Hi @ElinorG11,
Normally, we do not really support quantized weights, since the whole purpose of the toolkit is to simulate memristive in-memory compute, where weights are represented by conductances that naturally are analog values and cannot be quantized.  So the proper simulation to see the importance of the exact weight value is the sweep the (instantaneous) weight noise, which is set by the by the `rpu_config.forward.w_noise` parameter. Or alternatively, for inference only (using `RPUInferenceConfig`), one can increase the programming weight noise by increasing `rpu_config.noise_model.prog_noise_scale` which effectively reduces the precision of the weights written to the conductance values.   

That being said,  in case of inference only, you can of course just loop through the analog layers, get weights, quantize and set the weights again. If you model is of type `AnalogSequential` you can use `_apply_to_analog` (see [here](https://github.com/IBM/aihwkit/blob/master/src/aihwkit/nn/modules/container.py#L44)) to do something like:
```python
def quantize(mod):
    weight, bias = mod.get_weights()
    weightq = quantize(weight)  # your quantization method
    mod.set_weights()

# this loops through all analog modules and applies the above function :
model._apply_to_analog(quantize)
```    

Hope that helps.

**Comment by ElinorG11** [comment]
Thank you very much!!
