### ISSUE TITLE
cuda.is_compiled return false

### ISSUE THREAD

**Issue by jimmyli-421** [IBM/aihwkit#357]
Hello,

I have a question about cuda.is_compiled **return false** on version 0.5.0.

When I install aihwkit, the following steps and cuda.is_compiled will return true. (aihwkit version is 0.4.0 and Torch version is 1.8.0)
`!wget https://aihwkit-gpu-demo.s3.us-east.cloud-object-storage.appdomain.cloud/aihwkit-0.4.5-cp37-cp37m-manylinux2014_x86_64.whl`
`!pip install aihwkit-0.4.5-cp37-cp37m-manylinux2014_x86_64.whl`

But when using `pip install aihwkit`  to install aihwkit, the cuda.is_compiled return False. (aihwkit version is 0.5.0 and Torch version is 1.10.0)

Thank you very much for your help.

**Comment by maljoras** [comment]
Hi @jimmyli-421:

this is because the first one was compiled with CUDA and the second one is not compiled with CUDA. So naturally, the `is_compiled` flag is different. Currently, we do not have a pip version that is compiled with CUDA. If you want the current version compiles with CUDA, you can clone it from github and then compile it on your system. Please follow the [installation instructions](https://aihwkit.readthedocs.io/en/latest/developer_install.html) how to do that. If you have a linux system with properly installed CUDA drivers it is as simple as calling `make build_cuda`. For windows, there are [separate instructions](https://aihwkit.readthedocs.io/en/latest/advanced_install.html#windows-using-conda-experimental)

**Comment by jimmyli-421** [comment]
Thanks for helping!
I tried it, and it works!!!!

**Comment by meicale** [comment]
I build on wsl2_ubuntu 22.04 with torch1.13 and cuda 11.7 and it gives me :
```
[ 98%] Building CXX object src/aihwkit/simulator/CMakeFiles/rpu_base.dir/rpu_base_src/rpu_base_tiles_cuda.cpp.o
[100%] Linking CXX shared module rpu_base.cpython-39-x86_64-linux-gnu.so
......
```
does it completed? I can run the code but cuda.is_compiled is 0.
