### ISSUE TITLE
Setting the desired device precision

### ISSUE THREAD

**Issue by saba-er** [IBM/aihwkit#366]
The bit precision (or conductance levels) of memristive device does not seem to be configurable. It might be useful to have this feature at least for a conceptual device, if not feasible for device presets implemented through calibration. This feature is available in simulators such as MemTorch or NeuroSim.

**Comment by maljoras** [comment]
Hi @SaBaKa2020 ,
Many thanks for the request! Could you maybe specify in more detail what you mean by specifying the conductance precision? Obviously, conductance is an analog quantity and it makes physical no sense to specify resolution for that directly. 

For training, the way to specify the resolution implicitly is by setting the minimal width of the conductance response of a single pulse. This can be set with the parameter dw_min in most device models. Variations can be defined, too.

For inference only hardware designs, the programing noise will increase if devices are less precise, we offer a programming noise scale for that.

Some designs in the literature are using multiple devices with different significance to encode bits of a integer number, are you referring to this bit slicing method ?

Using multiple devices per cross point with different significances is also supported by using the VectorUnitCell.

So, it would be great if you could explain in more detail what you mean by precision of analog weights.

**Comment by SaBaKa2020** [comment]
Thanks for the elaborate answer. 
Maybe an example could help better clarify. Assume I would like the device to offer single bit precision (i.e. be programmed only in two states, for example high resistance and low resistance). How is it possible to configure this behavior in a device such as PCM which by nature offer around 50 reliable states? The reason I am interested in this kind of operation is twofold: 1) my weights are binary, for example they belong to a binary Ed neural network, 2) with reduced number of required states, one can program the device so that each two states will be sufficiently apart in terms of the corresponding conductance levels and hence more robust to noise (correct?).
I think my question applies mostly to inference phase. I am also aware of synaptic bit slicing which is a different topic. But slicing is useful when higher numeric precision for weights are needed.

**Comment by maljoras** [comment]
I understand that you are only interested in the inference case. For that, I don't see any problem of just programming the binary network you have into the analog devices, e.g. using the PCM like noise model. This will scale the largest value to gmax and the smallest to -gmax with the expected programming noise and you can test the expected accuracy. 

If you are interesting in the effect of larger programming noise, you can scale the programming noise scale or simply add your own programming noise model (by overriding the base noise model). In general, the number of states can be defined by dividing the conductance range by the expected noise standard deviation for the programming (but note that programming noise typically depends on the conductance value as well). So if you scale the programming noise you can investigate the effect of "reliable states". Not sure how other frameworks allow for adjustment the number of states of conductances, but it seems a little misleading to me.

**Comment by SaBaKa2020** [comment]
Thanks for the elaborate answer.
