### ISSUE TITLE
How to enable double precision?

### ISSUE THREAD

**Issue by ZhenmingYu** [IBM/aihwkit#396]
## Description and motivation
I am currently trying to develop a new device model for aihwkit that allows inputs with pulse voltage and pulse length and such.
Currently, it's not changing the weights in an analog way, but if I use a really long pulse length, my device is able to switch binary between w_min and w_max.

I assume there are some rounding issues in my code and would like to quickly check that out by setting everything in double precision.

I see that at the end of almost every source code file with lines like:

https://github.com/IBM/aihwkit/blob/f83a015283820748eee4214f298ee3ae2441d651/src/rpucuda/rpu_buffered_transfer_device.cpp#L297-L300

Where should one define the RPU_USE_DOUBLE so that aihwkit can be compiled with double precision?

## Proposed solution

Add a compilation option to enable double precision. And add this option to the documentation.

## Alternatives and other information

Some guidance on how to test the C code, and information where could I print out my variables in C are of course helpful as well.
There are `printDP` functions defined everywhere, but they are not accessible from python once compiled.

**Comment by maljoras** [comment]
Hi @ZhenmingYu ,
many thanks for the questions. Indeed, RPU_USE_DOUBLE is a somewhat "hidden" feature. It is not tested currently, and not exposed to pytorch, so it is turned off by default. You could, however, try to enable it by adding the compile flag `-DRPU_USE_DOUBLE=ON`. It might result in compilation errors, as it is not tested.  

However, using double precision should not be necessary. There typically is a large amount of weight noise, so that it is hard to justify that float32 is not enough to represent the weight values. Using float32 is also much fast than using double on GPUs, that's why we have disabled the double feature. 

In regards to testing the C code, you could just use standard C++ notation, e.g. `std::cout << varname << std::endl; ` to print a value to standard out. Using GDB is another possibility. Please take a look at the C++ testing scripts to get an impression how to run and write C++ tests. You can compile C++ testing scripts with the flag `-DBUILD_TEST=ON`.  See e.g. [here](https://github.com/IBM/aihwkit/blob/master/src/rpucuda/rpu_transfer_device_test.cpp). Here you can simply call printDP. 

If you want to verify from python, you can also use the `get_hidden_parameters()` function which will copy all the hidden device parameters (DP) to the python workspace, including the hidden weights. That might be more convenient. So you could update once, then use `get_hidden_parameters()` to check whether the hidden weight got updated in the correct fashion.

**Comment by ZhenmingYu** [comment]
Dear @maljoras 

Thanks for answering all the questions.

I think I have finished implementing all the required CUDA functions.

However, when testing it out with Pytorch, I got this error message in the python terminal:
`Segmentation fault (core dumped)`

I know from googling that this should be related to accessing a pointer that hasn't been allocated.
But I'm having trouble finding out where exactly caused this problem.

I tried as you suggested by building the project the `-DBUILD_TEST=ON` flag:
`python setup.py build_ext --inplace -DUSE_CUDA=ON -DRPU_CUDA_ARCHITECTURES=86`
But I was not able to find the executable after compilation.

Is there a proper way to debug the CUDA devices?

Thanks a lot!

Zhenming

**Comment by maljoras** [comment]
Did you write a c++ test file (one that ends with '*_test.cpp' in the cuda folder)? If so it will be placed in the `_skbuild/(op version)/cmake-build/rpu` folder if you build the tests with `-DBUILD_TEST=ON`.

Regarding your segmentation fault, that usually means that you have some memory issue on the CPU side such as accessing an array without initializing it. CUDA errors typically do not cause segmentation faults but separate errors. 

One does typically use `gdb` and `cuda-gdb` to debug the CUDA code, but unfortunately it can be tricky to do that. However, it typically will give you the line which is problematic. It is best to write a test file to check whether CUDA is behaving as expected. For instance, I have a standard test to check whether CUDA and CPU devices are performing the same thing, which you might be able to adapt to your device, ie you could add your device [here](https://github.com/IBM/aihwkit/blob/master/src/rpucuda/cuda/rpucuda_pulsed_device_test.cpp#L263).

**Comment by ZhenmingYu** [comment]
Dear @maljoras 

Thanks for answering.

During the Python tests, the `Segmentation fault (core dumped)` error comes at the [opt.step()](https://github.com/IBM/aihwkit/blob/master/examples/01_simple_layer.py#L58) line.
If I comment out the [move to cuda lines](https://github.com/IBM/aihwkit/blob/master/examples/01_simple_layer.py#L41-L44), and let the model run on CPU, this error would not appear.
So, I'd assume it's something related to the update step for CUDA. 

I tried with the c++ test file and was able to trace the update operations to [START_SINGLE_FUNCTOR](https://github.com/IBM/aihwkit/blob/master/src/rpucuda/cuda/pwu_kernel_parameter.h#L171-L181), where I can still `printf()` and verify that the `else` branch was executed.

However, it seems that `printf()` does not work any more within kernels, and would not continue to print inside [kernelUpdateWFunctor](https://github.com/IBM/aihwkit/blob/master/src/rpucuda/cuda/pwu_kernel.h#L309-L330), and also not inside my own `UpdateFunctor` that I wanted to test.

Is there anything else that you would recommend for debugging inside CUDA kernels?

Thanks for your patience!

Zhenming
