### ISSUE TITLE
set_weights taking 40 minutes for a 150x150 matrix

### ISSUE THREAD

**Issue by joris-gentinetta** [IBM/aihwkit#450]
## Description
The set_weights function of AnalogLinear takes a lot of time for weight matrices bigger than 50x50 (43 minutes for 150x150) when **realistic_read_write** is set to True.

## How to reproduce

import torch
from time import time
from aihwkit.simulator.presets.configs import PCMPreset, MixedPrecisionPCMPreset
from aihwkit.nn import AnalogLinear

rpu_config = MixedPrecisionPCMPreset()
realistic_read_write = True

init_weights = torch.zeros((150,150))

layer = AnalogLinear(150, 150, rpu_config=rpu_config, bias=False, realistic_read_write=realistic_read_write) 

start = time()
layer.set_weights(init_weights, force_exact=False)
end = time()
print((end-start)/60)

## Output
42.9 (minutes)

## Other information

Pytorch version: 1.13.0
Package version: dev install
OS: macOS Ventura 13.0.1 (Intel)
Python version: 3.8.15
Conda version (or N/A): 4.12.0

**Comment by maljoras** [comment]
Hi @joris-gentinetta,
many thanks for opening the issue. 

Realistic write means that the weights are iteratively programmed until convergence. It is almost like a full training simulation. Since the stochastic pulsing and device noise is simulated, it indeed takes time in particular on CPU (it is much faster on GPU) depending on the settings. Note that even in reality iterative programming of analog chips may take a long time.  If you are interested in analog training (with SGD and mixed precision) then it is advisable to just set `realistic_read_write=False` since the PCM devices are anyway randomly initialized. Note also, that  `realistic_read_write` is indeed using standard SGD and not mixed precision, so if you really want to study the writing, you could just implement it with AnalogLinear and torch losses (requiring the MSE of target output and actual output to be small) using `MixedPrecision`. 

If you are interested in inference only and want to program a weight matrix, you should use the `InferenceRPUConfig` and the statistical programming model to program the weights.

**Comment by joris-gentinetta** [comment]
Thanks for the fast reply!
