### ISSUE TITLE
Additional options to control pulse update on each device

### ISSUE THREAD

**Issue by chaeunl** [IBM/aihwkit#53]
https://github.com/IBM/aihwkit/blob/670a3141596556e34e4372774a5d609728fc064a/src/rpucuda/rpu_difference_device.cpp#L119

To make use of reference devices which correspond to the value "0" of weights, pulse updates should be controlled for each device. The behavior of reference devices is described at the paper, [1]. It would be convenient for users to have the following options:
1) Fix the conductance of reference device and the other device is the only one to be updated by pulses.
2) Can modulate updating the reference device not only to make use of sort of techniques such as zero-shifting [1], but also to design custom update rules for the device.

**In addition, it is recommended for every devices inherited from "aihwkit.simulator.configs.devices.PulsedDevice" base to have the reference device. So, I think that it would be better for you to modify the code at the level of device class, "rpu_pulsed.h" and "rpu_pulsed.cpp"**

[1] Kim, Hyungjun, Malte Rasch, Tayfun Gokmen, Takashi Ando, Hiroyuki Miyazoe, Jae-Joon Kim, John Rozen, and Seyoung Kim. "Zero-shifting Technique for Deep Neural Network Training on Resistive Cross-point Arrays." arXiv preprint arXiv:1907.10228 (2019).

**Comment by diego-plan9** [comment]
Thanks for your suggestion and for the detailed outline @chaeunl ! @maljoras will be able to follow-up on the discussion.

**Comment by maljoras** [comment]
Hi @chaeunl:
Thank you for the suggestion. I have now added a `ReferenceUnitCell` that can be used to implement the suggested behavior, see PR #61. 

It does _not_ modify the RPUPulsed behaviour (as you suggested) because in many cases one might actually not be interested in having an explicit reference device, as it can be handily modelled and abstracted away by increasing the noise level of the output instead of having an explicit representation. When one is nevertheless interested in a more detailed simulation, one can now use this `ReferenceUnitCell`. Note that one can use `UnitCells` as devices for `unit_cell_devices` thus this device can be used eg for both Tiki-taka devices as well and is thus not restrictive in any way, as arbitrary device pairs can be defined. 

Also, if you want to have e.g. 4 unit cell devices that share a reference cell, this can be implemented as well with the new `gamma_vec` property of `VectorUnitCells` that explicitely specifies the weight/significance of the devices  (although one would need to set the `update_idx` manually, if this is really needed by someone, we add more `update_policy` types that e.g. randomly select only a subset of available devices in future)

**Comment by maljoras** [comment]
@chaeunl I slightly updated my comments above. Currently, the device types actually need to be the same for those single devices composing  ``VectorUnitCell`` and ``ReferenceUnitCell`` (only in case of CUDA; for CPU, they are arbitrary). This is because of how we do auto-tuning of the CUDA-kernels to optimize for speed (the tuned kernels are shared among all unit cell devices and thus their update type needs to be the same). However, that might not be a strong restriction, as different device materials for devices within a single unit cell is a rather strange situation in reality anyway. We can open another issue if that is needed.
