### ISSUE TITLE
 Considering weight updates for half-biased devices

### ISSUE THREAD

**Issue by Seungkun-Kim** [IBM/aihwkit#619]
Hello. I am currently trying to confirm the **impact of the half-bias scheme in deep neural network training with resistive cross-point array**. 

I aim to investigate how weight changes occur not only in selected devices based on the coincidence of pulses, as discussed in the RPU paper  #(T. Gokmen and Yurii Vlasov, 2016), but also in **half-selected (or half-biased) devices, and how this influences test errors in various training algorithms such as SGD, TTv1, TTv2, c-TTv2, and AGAD.**

Upon examining the C++ code, particularly in `aihwkit/src/rpucuda sparse_bit_line_maker.cpp`, I observed that **d_count is returned**, and in `aihwkit/src/rpucuda rpu_weight_updater.cpp`, **d_count is checked** to determine whether a pulse coincidence has occurred, triggering the **doSparseUpdate function**.

So my questions are:

1.	Are updates triggered only by the coincidence of Activation Vector and Error Vector?
2.	Is it possible to consider updates of half-biased devices (i.e., half-updates) if vectors are non-zero but do not coincide?
3.	What are the differences between Dense update and Sparse Update?

**Comment by maljoras** [comment]
Hi @Seungkun-Kim,
currently half-select is indeed not considered and it would be a very good idea to add support for that. 

Indeed, the d_count / x_count are computed and it could be used for adding half-select.  While it is relatively straightforward to add the half-select changes before or after handling the coincidences, this is not quite correct, as the temporal order of the updates need to be conserved (most update models are highly non-linear). This makes it more challenging to implement half-select in fast way.

The dense and sparse update routines have the same function, however, since coincidences are typically very sparse, the sparse updater optimizes the compute by considering and storing only the indices to update. The dense optimizer does not do that, as it computes the update counts on the fly from some deterministic pulsing mode or probability distribution.

One way to approach the half-select could be to approximate the temporal ordering and simply add the half-select at the beginning or end of the coincidence loop. In that case, one has the wrong temporal order, but it would be a simple implementation and approximately correct at least when updates are very sparse (which is the usual case).  However, this might be problematic for GPU with large  batch sizes, as the batch is loaded and all sparse updates are added in a very optimized fashion for acceleration. In this case, this approximation might be too inaccurate.  On the other hand, it would be impacting the speed quite a bit if half-select is done with the correct temporal ordering (as many weights have to be loaded into GPU memory for each thread), or one has to figure out a smart way to optimize the memory access pattern in the CUDA kernel for half-select, which would mean considerable implementation effort. This is basically the reason why we haven't tackled half-select so far. However, if you want to make a first step e.g. by implementating the approximation, that would be great!

**Comment by Seungkun-Kim** [comment]
Hi, @maljoras. Thank you for the detailed comments!

I understood that the existing update method is optimized for utilizing GPU memory for computational acceleration.

However, as long as the computational speed does not slow down too much or if temporal ordering can be approximated, it is thought that the influence of half-select on training can be examined even in simple tasks.

One method I'm considering to verify these effects is to extract the counts, indices, and sign information where coincidence occurs between **x_counts** (activations) and **d_counts** (errors) in spare_bit_line_maker.cpp, as done previously. Additionally, when there is no coincidence in **x_counts** and **d_counts**, (the counts, indices, and sign information) can be extracted separately. This information would then be integrated into **doSparseUpdate** in **rpu_weight_updater.cpp**. To apply the weight change when no coincidence occurs, an update_ratio (e.g., Ratio of x_counts = 0.4, ratio of d_counts = 0.2) would be introduced.

```
if (x_counts_p[k] > 0) {
  rpu_device->doSparseUpdate(weights, i, x_indices_p[k], x_counts_p[k], d_sign, &*rng_);
}
if (do_negative_separatly) {
  if (x_counts_n[k] > 0) {
    rpu_device->doSparseUpdate(
        weights, i, x_indices_n[k], x_counts_n[k], d_sign, &*rng_);
```

Subsequently, when **doSparseUpdate** is invoked in **rpu_device**, if the device is a softbound synapse, the **update_once_mult** or **update_once_add** operation will eventually be performed in **rpu_softbounds_reference_device.cpp**.

```
if (par.mult_noise) {
  PULSED_UPDATE_W_LOOP(update_once_mult(
                           w[j], w_apparent[j], sign, scale_down[j], scale_up[j], ref[j],
                           min_bound[j], max_bound[j], par.dw_min_std, write_noise_std, rng););
} else {
  PULSED_UPDATE_W_LOOP(update_once_add(
                           w[j], w_apparent[j], sign, scale_down[j], scale_up[j], ref[j],
                           min_bound[j], max_bound[j], par.dw_min_std, write_noise_std, rng););
}
```
In this proposed method, considering three cases: 1) when coincidence occurs (update_ratio: 1), 2) when no coincidence occurs in **x_counts** (update_ratio: 0.4), and 3) when no coincidence occurs in **d_counts** (update_ratio: 0.2), the weight update would be changed and performed as follows:
`w -= update_ratio * (scale_down * ((T)1.0 - a) * ((T)1.0 + dw_min_std * rng->sampleGauss()));`

Although I wish to apply this method to test it, there are several challenges. Therefore, my questions are :

1. In which code in **spare_bit_line_maker.cpp** is the counts, indices, and sign information of a coincidence calculated? Also, can I extract information such as counts, indices, and signs of **x_counts** and **d_counts** when no coincidence occurs?
2. Is **x_counts** split between p and n, but **d_counts** has no sign information?

I'm sorry for having many questions.

Thank you!

**Comment by maljoras** [comment]
Sparse bit lines is highly optimized code that *only* stores the indices of the 1s of x and d inputs. Counts is simply the number of indices stored which is the number of 1s of each input line. 

I would think it would be best if you make a separate file for your new pulsing scheme. Changing the existing one might be difficult and introduce errors.

But I agree the update_once is called for each coincidence. I guess one has to add a "update_once_half" for each synapse and call it from a new bitline maker when a hald-update is done. The half-update itself should be a method of each synapse.

**Comment by Seungkun-Kim** [comment]
Thank you for the reply. I'll try to change it based on your answer!
