### ISSUE TITLE
ImportError: cannot import name 'AnalogSGD' from 'aihwkit.optim'

### ISSUE THREAD

**Issue by spwjr** [IBM/aihwkit#65]
## Description
I tried to run the py files under  tests/ and examples/ but it will return an error: ImportError: cannot import name 'AnalogSGD' from 'aihwkit.optim'

## How to reproduce
python tests/test_utils.py

## Other information
Follow the installation guide and python version is 3.7.3 

* Pytorch version:
* Package version:0.2
* OS:MAC Catalina
* Python version: 3.7.3
* Conda version (or N/A):

**Comment by diego-plan9** [comment]
Hi @spwjr ,

and thanks for reporting! It seems there might be a mismatch between the version of `aihwkit` that you are using (which I'm assuming you installed from `pip`) and the "version" of the examples that you are using (in this case, I'm assuming you are using the `master` branch from this repo).

If that is the case, the `master` branch contains code that has not been released as a stable version in pip yet - in a way, it is ahead by some commits. In particular, at #54 we introduced a more comfortable `from aihwkit.optim import AnalogSGD` way to import the optimizer instead of the previous `from aihwkit.optim.analog_sgd import AnalogSGD`.

In order to solve the mismatch, can you try either:
1. using the examples from the [`v0.2.0` tag](https://github.com/IBM/aihwkit/tree/v0.2.0) instead of the `master` branch: that tag contains the codebase (including tests and examples) at the time the 0.2.0 release was made. If you cloned the repository, `git checkout v0.2.0` would change to the right tag.
2. use the code from the `master` branch instead of the pip-installed 0.2.0 release - this involves some more steps (most notably compilation, and dealing with the pythonpath - they are hopefully outlined at [the docs](https://aihwkit.readthedocs.io/en/latest/developer_install.html)) for setting up the development environment, but would allow you to use the new features introduced after `0.2.0`.

**Comment by spwjr** [comment]
Thanks Diego
I tried both 
1:switch to v0.2.0 tag and it works !
2:with a new terminal and virtual env I have tried the method described in the Development setup page
and running the example from master branch, it will show error regarding symbol can not be found,  for example
from aihwkit.simulator.rpu_base import devices
ImportError: dlopen(/ibm_test/aihwkit_env/lib/python3.7/site-packages/aihwkit/simulator/rpu_base.cpython-37m-darwin.so, 2): Symbol not found: __ZN3c104impl23ExcludeDispatchKeyGuardC1ENS_11DispatchKeyE
Referenced from: /project/ibm_test/aihwkit_env/lib/python3.7/site-packages/aihwkit/simulator/rpu_base.cpython-37m-darwin.so
  Expected in: flat namespace
 in /project/ibm_test2/aihwkit_env/lib/python3.7/site-packages/aihwkit/simulator/rpu_base.cpython-37m-darwin.so

The following are the steps I have tried based on the help page, please correct me if I missed some steps.
1:python3 -m venv aihwkit_env
2:cd aihwkit_env/
3:source bin/activate
4:git clone https://github.com/IBM/aihwkit.git
5:brew install openblas
6:pip install cmake scikit-build torch pybind11
7:pip install -v aihwkit
8:python setup.py build_ext --inplace

**Comment by diego-plan9** [comment]
Thanks for the detailed feedback @spwjr ! Can you attach the output of your last step (`python setup.py build_ext --inplace`)? Specifically, for trying to see which compiler are you using, which we can verified by the output of the command in a line similar to:

```
-- The CXX compiler identification is ...
```

In `osx`, we currently recommend using the compiler that is part of the latest Xcode (`Apple clang`), and  it might be that you are using `gcc` and running into an issue similar to https://github.com/RcppCore/RcppArmadillo/issues/224#issuecomment-386943484 (thanks to @maljoras for the pointer!). If the command is picking up `gcc` automatically, can you try instructing it to use `clang` via:

```
python setup.py build_ext --inplace -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++
```

And see if the `Symbol not found` reappears?

**Comment by spwjr** [comment]
Hi Diego
     Thanks for the feedback, 
- The C compiler identification is AppleClang 12.0.0.12000032
-- The CXX compiler identification is AppleClang 12.0.0.12000032

after I use python setup.py build_ext --inplace -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++
it stop and report an error
/project/ibm_test/aihwkit_env/lib/python3.7/site-packages/torch/include/torch/csrc/python_headers.h:17:2: error: 
      "Python 2 has reached end-of-life and is no longer supported by PyTorch."
#error "Python 2 has reached end-of-life and is no longer supported by PyTorch."
n file included from /project/ibm_test/aihwkit_env/aihwkit/src/aihwkit/simulator/rpu_base_src/rpu_base.cpp:13:
An error occurred while building with CMake.
  Command:
    cmake --build . --target install --config Release --
  Source directory:
   /project/ibm_test/aihwkit_env/aihwkit
  Working directory:
    /project/ibm_test/aihwkit_env/aihwkit/_skbuild/macosx-10.15-x86_64-3.7/cmake-build

**Comment by diego-plan9** [comment]
Interesting - it seems that for some reason the build system is picking up the wrong Python version during your latest run.

Can you:
* verify that you are running the command inside your activated `aihwkit_env` virtualenv (it _seems_ to be the case, but just for double-checking)
* run `make clean` and remove the `_skbuild` directory (it is a temporary folder used by the build system for caching: by removing it, we ensure you attempt compiling in a "clean" state)
* try compiling again and attach the log of the output? In the same way it prints some information about the compiler identification, it also outputs information about the Python version it identified, ie:

```
...
-- Found PythonInterp: ...
-- Found PythonLibs: ...
-- Found Python: ...
-- Found Torch: ...
```

In the same spirit as the flags for overriding the compiler detection, there are some flags that you can pass to `setup.py` that allow pointing the build system to a specific Python version:

```
-DPYTHON_EXECUTABLE=/something -DPYTHON_INCLUDE_DIR=/somethingelse -DPYTHON_LIBRARY=/other
```

The values for those variables would be the related to your virtualenv - however, let's see if we can find out why it is not picking the right ones automatically, which is much more convenient and fail-proof.

**Comment by spwjr** [comment]
Thanks Diego, the execution path is under aihwkit_env 
I did your suggestion : make clean and re-run python setup.py build_ext --inplace -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++
the log shows the version below
-- Found OpenBLAS libraries: /usr/local/opt/openblas/lib/libopenblas.dylib
-- Found OpenBLAS include: /usr/local/opt/openblas/include
-- Found PythonLibs: /Users/xxx/.pyenv/versions/3.7.3/lib/libpython3.7m.a (found version "3.7.3") 
-- Found PythonInterp: /Users/xxx/project/ibm_test3/aihwkit_env/bin/python (found version "3.7.3") 
-- Found PythonLibs: /Users/xxx/.pyenv/versions/3.7.3/lib/libpython3.7m.a
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- Performing Test HAS_FLTO_THIN
-- Performing Test HAS_FLTO_THIN - Success
-- Found pybind11: /Users/xxx/project/ibm_test3/aihwkit_env/lib/python3.7/site-packages/pybind11/include (found version "2.6.1" )
-- Found Python: /Users/xxx/project/ibm_test3/aihwkit_env/bin/python3 (found version "3.7.3") found components: Interpreter 
-- Found Torch: /Users/xxx/project/ibm_test3/aihwkit_env/lib/python3.7/site-packages/torch/include;/Users/xxx/project/ibm_test3/aihwkit_env/lib/python3.7/site-packages/torch/include/torch/csrc/api/include  
-- Configuring done
-- Generating done

The result of error message from executing example is the same, thanks

**Comment by diego-plan9** [comment]
Thanks for the detailed output - it seems on this round indeed it picked up the right compiler, _and_ the right Python. Assuming that the compilation ended successfully:

> The result of error message from executing example is the same, thanks

Do you mean that the error you get is this one from https://github.com/IBM/aihwkit/issues/65#issuecomment-723367269? 
```
from aihwkit.simulator.rpu_base import devices
ImportError: dlopen(/ibm_test/aihwkit_env/lib/python3.7/site-packages/aihwkit/simulator/rpu_base.cpython-37m-darwin.so, 2): Symbol not found: __ZN3c104impl23ExcludeDispatchKeyGuardC1ENS_11DispatchKeyE
Referenced from: /project/ibm_test/aihwkit_env/lib/python3.7/site-packages/aihwkit/simulator/rpu_base.cpython-37m-darwin.so
Expected in: flat namespace
in /project/ibm_test2/aihwkit_env/lib/python3.7/site-packages/aihwkit/simulator/rpu_base.cpython-37m-darwin.so
```

If the paths shown are similar (specifically, if they include `lib/python3.X/site-packages`) this likely points to `aihwkit` being installed in the virtualenv, and when executing, is trying to use the downloaded library instead of the library that you just compiled - and actually, if that is the case, it seems you are being hit by #52.

So, in order to make sure that you use the compiled library from `master` for running the examples, can you:
* remove the installed stock version of `aihwkit`:
   ```
   $ pip uninstall aihwkit
   ```
* rebuild the shared library (likely not really needed, but just for making sure):
  ```
  $ make clean
  $ python setup.py build_ext --inplace -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++
  ```
* run the examples with the right `PYTHONPATH`
  ```
  PYTHONPATH=src/ python examples/1_simple_layer.py
  ```

And let me know if that does the trick? We'll look into tuning a bit more the [developer install](https://aihwkit.readthedocs.io/en/latest/developer_install.html) docs highlighting a bit more some particular points (the details about `PYTHONPATH`, for example) and adding others.

**Comment by HungYangChang** [comment]
Hello Diego,
Thanks for the detailed answer!
I got the same error like [this one](https://github.com/IBM/aihwkit/issues/65#issuecomment-723367269).
and after I tried prcodeure in the your new [post](https://github.com/IBM/aihwkit/issues/65#issuecomment-726683120)
$ make clean
$ python setup.py build_ext --inplace -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++
run the examples with the right PYTHONPATH
$ PYTHONPATH=src/ python examples/1_simple_layer.py
It is working now!

**Comment by spwjr** [comment]
Hi Diego 
    My part is also working now 
I don't uninstall aihwkit 
but just execute the following steps 
$ make clean
$ python setup.py build_ext --inplace -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++
PYTHONPATH=src/ python examples/1_simple_layer.py
Thanks for your help!

**Comment by HungYangChang** [comment]
For MacOS user, if you still get a similar error you can create a new path and follow the following procedure:

python3 -m venv aihwkit_env
cd aihwkit_env/
source bin/activate
cd aihwkit
git clone https://github.com/IBM/aihwkit.git
brew install openblas
pip install cmake scikit-build torch pybind11
pip install -v aihwkit
pip install torch torchvision torchaudio
(optional) pip install matplotlib
make clean
python setup.py build_ext --inplace -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++
PYTHONPATH=src/ python examples/1_simple_layer.py

Hope this one help :)

**Comment by jhu960213** [comment]
Hello, 

I'm following the exact same steps like the ones listed above but I run into this error instead which is weird because I've checked that this package has indeed been installed via pip:

- says it couldn't find pybind cmake config path and also I think after fixing this error the build phase will result in another error saying that it can not find torch path but the torch has been installed just like pybind11

![Screen Shot 2020-11-15 at 6 51 35 PM](https://user-images.githubusercontent.com/20133323/99200506-be28cf80-2773-11eb-90a1-96b66a8a7059.png)

Steps I've followed: 
python3 -m venv aihwkit_env
cd aihwkit_env/
source bin/activate
cd aihwkit
git clone https://github.com/IBM/aihwkit.git
brew install openblas
pip install cmake scikit-build torch pybind11
pip install -v aihwkit
pip install torch torchvision torchaudio
(optional) pip install matplotlib
make clean
python setup.py build_ext --inplace -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++
PYTHONPATH=src/ python examples/1_simple_layer.py

Note: I'm using python 3.8.6 would this be a problem?

**Comment by jhu960213** [comment]
@diego-plan9 Do you know what's going on? Thanks!

**Comment by diego-plan9** [comment]
@spwjr and @HungYangChang - glad that you have been able to compile, and thanks as well for sharing your tips and flows! It does help everyone that might be facing similar problems. As hinted earlier, I'll try to revise/extend the docs to reflect the conversation.

@jhu960213 from the screenshot, I think we can chalk it (at least partially) to a `_skbuild` caching issue - the screenshot seems to be missing some lines that are only printed when starting from a clean state. The `_skbuild` folder helps in a number of cases (for example, if modifying the c++ files, allowing to only recompile the changed bits), but the caching unfortunately is not smart enough for bigger changes such as changing dependencies, etc. It's also a bit out of our control, so in case of doubt removing the `_skbuild` folder (or running `make clean` since #69) is recommended before compiling.

> Also is there a way to make aihwkit work with Jupiter notebooks?

Would you mind opening a new issue with the issues you might be encountering related to Jupyter? In theory it should be a matter of making jupyter aware of the right `PYTHONPATH` (in the case of compiling manually).

**Comment by HungYangChang** [comment]
Hello! @diego-plan9 

@jhu960213  is one of my partners, now it seems he already solved the problem.  I will let them post his flow later.
As for opening a new issue for Jupyter setting. We will try it later and report our problems.

Thanks!

**Comment by jhu960213** [comment]
@diego-plan9 Thanks for the advice I will do that from now on! And I will also make an issue about the Jupyter notebook!

As for the flow of my current setup if anyone else had been experiencing caching related issues I suggest doing the following:
1) delete the _skbuild folder or do $ make clean before building with setup.py
2) Follow the flow posted by @HungYangChang:

python3 -m venv aihwkit_env
cd aihwkit_env/
source bin/activate
cd aihwkit
git clone https://github.com/IBM/aihwkit.git
brew install openblas

****Note: now instead of installing all the dependencies with pip activate conda and install all of them using conda forge 
or from any of their repositories and make sure the versions match with the ones listed in the advanced installation guide.****

make clean (just to be sure...optional at this point if you've already removed the _skbuild folder)
python setup.py build_ext --inplace -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++
PYTHONPATH=src/ python examples/1_simple_layer.py

Then after all this, it should work hopefully..... :) 
-J.H

**Comment by diego-plan9** [comment]
Closing as part of the 0.3 release cleanup - thanks for all the feedback and information, and don't hesitate on opening a new issue or commenting back if needed, as there has been quite some changes included in the release.
