### ISSUE TITLE
Version issues during pip installation in the Advanced Installation Guide

### ISSUE THREAD

**Issue by sheep1222** [IBM/aihwkit#689]
Firstly, I believe this is a great work, and I would like to thank you for your contributions in the field of memristive neural networks. As a beginner, I only want to use this tool quickly and easily, so I followed the pip commands in the Advanced Installation Guide to install the GPU version of aihwkit. However, I have learned that the latest version is 0.9.1. Can I replace 0.8.0 in the commands with 0.9.1 to download the latest version? Will this cause any environmental conflicts? I haven't made such an attempt yet. I will try it next and look forward to your reply.

**Comment by kaoutar55** [comment]
Please give it a try and let us know if anything goes wrong. Can you also try the conda command?

**Comment by PabloCarmona** [comment]
We need to update the docs with our new release, thanks for point it out @sheep1222. As @kaoutar55 suggested go with the conda install, it's simpler and better, but if you want to do it with pip until we do the new release do the following command, because the versions of the kit and the CUDA should match properly:

```bash
$ wget https://aihwkit-gpu-demo.s3.us-east.cloud-object-storage.appdomain.cloud/aihwkit-0.9.1+cuda117-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl

$ pip install aihwkit-0.9.1+cuda117-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
```

Hope this solve your doubts! And thanks for try out the project!

**Comment by sheep1222** [comment]
@kaoutar55 @PabloCarmona Thank you for your reply. I will try two methods in the coming time, and if there are any problems, I will point them out.
